name: arm64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: clone scummvm
      run: git clone https://github.com/janisozaur/scummvm
    - name: show git head
      run: git --no-pager show HEAD
    - name: install boost-build
      run: vcpkg.exe install boost-build
    - name: install libs
      run: vcpkg.exe install libpng:arm64-windows freetype:arm64-windows curl:arm64-windows libjpeg-turbo:arm64-windows sdl2:arm64-windows sdl2-net:arm64-windows libvorbis:arm64-windows libmad:arm64-windows libogg:arm64-windows libflac:arm64-windows libtheora:arm64-windows fluidsynth:arm64-windows
    - name: export libs
      run: |
          vcpkg.exe export libpng:arm64-windows freetype:arm64-windows curl:arm64-windows libjpeg-turbo:arm64-windows sdl2:arm64-windows sdl2-net:arm64-windows libvorbis:arm64-windows libmad:arm64-windows libogg:arm64-windows libflac:arm64-windows libtheora:arm64-windows fluidsynth:arm64-windows --zip
          mkdir export
          cp *.zip export
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-libs
        path: D:\a\vcpkg\vcpkg\export
      if: always()
    - name: build scummvm
      run: |
        cd scummvm
        cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows . -A Arm64
        cmake --build
        echo janis building
        cmake --build . -j
