name: arm64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: list dir
      run: ls
    - name: show git head
      run: git --no-pager show HEAD
    - name: install boost-build
      run: vcpkg.exe install boost-build
    - name: install boost-context
      run: vcpkg.exe install boost-context:arm64-windows-static boost-test:arm64-windows-static
    - name: show logs context
      if: always()
      run: type D:\a\vcpkg\vcpkg\buildtrees\boost-context\build-arm64-windows-static-rel-out.log
    - name: Download ninja
      if: always()
      run: |
        7z x ninja-win.zip -oC:\
        set PATH="C:\;%PATH%"
        ninja --version
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm64
        cl
        cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows-static bctest -G Ninja
        ninja -v
    - uses: actions/upload-artifact@master
      with:
        name: boost-context-buildtree
        path: D:\a\vcpkg\vcpkg\buildtrees\boost-context\
      if: always()
    - uses: actions/upload-artifact@master
      with:
        name: boost-context-buildtree
        path: D:\a\vcpkg\vcpkg\buildtrees\boost-context\
      if: always()
