name: x86_64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: install ninja
      run: |
          7z x ninja-win.zip -oC:\windows\system32
          ninja --version
          cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: clone scummvm
      run: git clone https://github.com/janisozaur/scummvm
    - name: show git head
      run: git --no-pager show HEAD
    - name: install boost-build
      run: vcpkg.exe install boost-build
    - name: install libs
      run: vcpkg.exe install libpng:x64-windows freetype:x64-windows curl:x64-windows libjpeg-turbo:x64-windows sdl2:x64-windows sdl2-net:x64-windows libvorbis:x64-windows libmad:x64-windows libogg:x64-windows libflac:x64-windows libtheora:x64-windows fluidsynth:x64-windows
    - name: export libs
      run: |
          vcpkg.exe export libpng:x64-windows freetype:x64-windows curl:x64-windows libjpeg-turbo:x64-windows sdl2:x64-windows sdl2-net:x64-windows libvorbis:x64-windows libmad:x64-windows libogg:x64-windows libflac:x64-windows libtheora:x64-windows fluidsynth:x64-windows --zip
          mkdir export
          cp *.zip export
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-libs
        path: D:\a\vcpkg\vcpkg\export
      if: always()
    - name: build scummvm
      run: |
        cd scummvm
        cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
        cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows . -GNinja
        ninja -v
    - name: show logs
      if: always()
      run: type D:\a\vcpkg\vcpkg\buildtrees\boost-context\build-x64-windows-rel-out.log
